

[functions]
[functions.generate-course]
verify_jwt = false

[functions.generate-course.test-connection]
verify_jwt = false

[functions.generate-course.test-claude]
verify_jwt = false

[functions.generate-course.public-debug]
verify_jwt = false

[functions.generate-course.full-diagnosis]
verify_jwt = false

[functions.generate-course.debug-cors]
verify_jwt = false

[functions.generate-course.check-env]
verify_jwt = false
