
project_id = "ittzxpynkyzcrytyudlt"

[functions.generate-course]
verify_jwt = true

[functions]
[functions.config]
allowed_domains = ["https://automator.ro", "http://automator.ro", "https://www.automator.ro", "http://www.automator.ro"]
