
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ittzxpynkyzcrytyudlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dHp4cHlua3l6Y3J5dHl1ZGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTcwNjcsImV4cCI6MjA2MDE5MzA2N30._NHAy4AFExT03NettnTE4J8SdodAh8nQb_78U1dzKj4";

// Improved client creation with domain awareness
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'X-Client-Info': 'automator-app'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);
